services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ysturasp-bot
    restart: unless-stopped
    ports:
      - '${PORT:-5500}:5500'
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-5500}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
    networks:
      - ysturasp-svelte_default

networks:
  ysturasp-svelte_default:
    external: true
