services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ysturasp-bot
    restart: unless-stopped
    ports:
      - '${PORT:-5500}:5500'
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-5500}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - PRIVATE_KEY=${PRIVATE_KEY}
    networks:
      - ysturasp-db

  redis:
    image: redis:7
    container_name: ysturasp-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - ysturasp-db

networks:
  ysturasp-db:
    external: true

volumes:
  redis-data:
